title: CV | A jekyll template
description:  A beautiful template for your CV.
url: https://apolaz.github.io/my-cv/
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll

exclude:
  - docker-compose.yml
